name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out the code from the repository
      - name: Build
        run: echo "building..."    # This placeholder step simulates the build process

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: |
          ssh user@frontend-machine "bash -s" <<'EOF'
            cd /path/to/frontend && git pull && npm install && pm2 restart all # Commands to deploy the frontend app
          EOF
